### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [fegennari/3DWorld#6]
[An extra null pointer check is not needed in a function](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like [the destructor for the class “VertData”](https://github.com/fegennari/3DWorld/blob/8f4cfb80ebac092d5ea3219f70499dcf41ece77d/src/triListOpt.h#L53 "Update candidate").

**Comment by fegennari** [comment]
Thanks. This isn't my code, I copied it from another project, but it's easy to change. I'm not sure if there are any more of these or how to find them.

**Comment by elfring** [comment]
How do you think about to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability-delete-null-pointer.html "Deletion of unnecessary null pointer checks")?

**Comment by fegennari** [comment]
Thanks, I'll look into this. There seems to be an option to run this in Visual Studio.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/fegennari/3DWorld/commit/ba293e8a06e38be09e65e24ef4387f368442a00e "Deletion of an unnecessary check").

**Comment by fegennari** [comment]
I removed the setting of triIndex back to NULL. I'm not sure it really matters. Sometimes it's useful to leave that in because it causes less trouble if that class is used after free. I have code like that to check for use-after-free in my universe ship logic, which has quite a complex object ownership/reference counting system due to the reference cycles between ships.
