### ISSUE TITLE
not an issue :)

### ISSUE THREAD

**Issue by Juris3D** [fegennari/3DWorld#8]
Hello! Juris from Latvia here, haven't been checking on your project for a while (in fact, making some UE4 assets now myself). How are you, what are advances in 3D World? My best wishes to you, be healthy!
And - Happy Easter !

**Comment by fegennari** [comment]
Hi Juris! I'm doing well, working from home now due to Covid 19. I'm still
actively working on the 3DWorld project. You can see some of my updates on
my blog: https://3dworldgen.blogspot.com. This past year I've mostly been
working on building interiors. I started by adding interior walls, floors,
ceilings, stairs, and elevators. Then I added furniture and appliances to
rooms, and small objects on tables/desks/shelves/drawers. The player can
pick up objects and interact with everything. I added people that walk
around inside buildings, open/close doors, and turn on/off lights. I've
turned it into a sort of game where you have to break into houses and steal
items without letting the people (zombies) get you. You can drink various
drinks you find as power-ups and throw things at the people. I also added
lots of exterior/city details (parks, helicopters, fire hydrants, solar
panels, etc.)

**Comment by fegennari** [comment]
Oh, and thanks, Happy Easter to you too!
